package hibernatecrud;
// Generated 24-ene-2019 20:07:28 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idcliente;
     private String nombre;
     private String dni;
     private String tlf;

    public Clientes() {
    }

    public Clientes(String nombre, String dni, String tlf) {
       this.nombre = nombre;
       this.dni = dni;
       this.tlf = tlf;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }




}


