package hibernatecrud;
// Generated 24-ene-2019 20:07:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private int idcoche;
     private String NBastidor;
     private String marca;
     private String modelo;
     private Set proveedoreses = new HashSet(0);

    public Coches() {
    }

	
    public Coches(int idcoche, String NBastidor, String marca, String modelo) {
        this.idcoche = idcoche;
        this.NBastidor = NBastidor;
        this.marca = marca;
        this.modelo = modelo;
    }
    public Coches(int idcoche, String NBastidor, String marca, String modelo, Set proveedoreses) {
       this.idcoche = idcoche;
       this.NBastidor = NBastidor;
       this.marca = marca;
       this.modelo = modelo;
       this.proveedoreses = proveedoreses;
    }
   
    public int getIdcoche() {
        return this.idcoche;
    }
    
    public void setIdcoche(int idcoche) {
        this.idcoche = idcoche;
    }
    public String getNBastidor() {
        return this.NBastidor;
    }
    
    public void setNBastidor(String NBastidor) {
        this.NBastidor = NBastidor;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set proveedoreses) {
        this.proveedoreses = proveedoreses;
    }




}


