package hibernatecrud;
// Generated 24-ene-2019 20:07:28 by Hibernate Tools 4.3.1



/**
 * Mecanicos generated by hbm2java
 */
public class Mecanicos  implements java.io.Serializable {


     private Integer idmecanico;
     private String nombre;
     private String dni;
     private String tlf;

    public Mecanicos() {
    }

    public Mecanicos(String nombre, String dni, String tlf) {
       this.nombre = nombre;
       this.dni = dni;
       this.tlf = tlf;
    }
   
    public Integer getIdmecanico() {
        return this.idmecanico;
    }
    
    public void setIdmecanico(Integer idmecanico) {
        this.idmecanico = idmecanico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }




}


