package hibernatecrud;
// Generated 24-ene-2019 20:07:28 by Hibernate Tools 4.3.1



/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private int idproveedor;
     private Coches coches;
     private String nombre;
     private String marca;

    public Proveedores() {
    }

	
    public Proveedores(int idproveedor, String nombre, String marca) {
        this.idproveedor = idproveedor;
        this.nombre = nombre;
        this.marca = marca;
    }
    public Proveedores(int idproveedor, Coches coches, String nombre, String marca) {
       this.idproveedor = idproveedor;
       this.coches = coches;
       this.nombre = nombre;
       this.marca = marca;
    }
   
    public int getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(int idproveedor) {
        this.idproveedor = idproveedor;
    }
    public Coches getCoches() {
        return this.coches;
    }
    
    public void setCoches(Coches coches) {
        this.coches = coches;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }




}


